<a href="https://colab.research.google.com/github/rafaelponte25/cuddly-chainsaw/blob/master/TensorFlow_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Fundamentals of TensorFlow TensorFlow**

Reference [video](https://www.youtube.com/watch?v=tpCFfeUEGs8)

## Introduction to Tensors

###Creating a Tensor

We will create a **Scalar** (a number), a **Vector** (a number with direction e.g. force and its direction), a **Matrix** (2-dimensional array of numbers), and a **Tensor** (n-dimensional array of number, where n can be any number).

In [5]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [6]:
#Create a tensor (check the definition with crtl -> shift -> space)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#Check the number of dimensions
scalar.ndim

0

In [8]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [10]:
#Create a matrix
matrix = tf.constant([[25.,5.],
                     [5.,25.]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[25.,  5.],
       [ 5., 25.]], dtype=float16)>

In [11]:
matrix.ndim

2

In [12]:
#create a tensor
tensor = tf.constant([
                      [[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9], [1, 7, 2]],
                      [[5, 3, 2], [3, 0, 8]]

])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 7, 2]],

       [[5, 3, 2],
        [3, 0, 8]]], dtype=int32)>

In [13]:
tensor.ndim

3

### Creating Tensors with tf.variable

Study changeable and unchangeable tensors

In [14]:
#Create tensor with tf.Variable
changeable_tensor = tf.Variable([25,5])
unchangeable_tensor = tf.constant([25,5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([25,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([25,  5], dtype=int32)>)

In [15]:
#Assign will only work for changeable tensors
changeable_tensor[0].assign(98)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([98,  5], dtype=int32)>

###Creating Random Tensors & Shuffling

Read about [random seed](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [20]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [28]:
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [50]:
#tf.random.set_seed(5)
tf.random.shuffle(not_shuffled, seed=25)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>